# Site settings
title: Rapt Aerial Dance
email: info@raptaerialdance.com
description: > # this means to ignore newlines until "baseurl:"
  Rapt Aerial Dance description...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://raptaerialdance.com" # the base hostname & protocol for your site
twitter_username: susanharkey
github_username:  susanharkey

# Build settings
markdown: kramdown
